### ISSUE TITLE
Subscribe method

### ISSUE THREAD

**Issue by highfeed** [s0ph1e/node-unisender#3]
Где?

**Comment by aivus** [comment]
Feel free to send pull requests.

**Comment by highfeed** [comment]
Что?

**Comment by s0ph1e** [comment]
@highfeed please, update to version 0.1.2

**Comment by highfeed** [comment]
Спасибо! Все отлично.

2015-05-01 17:00 GMT+03:00, Sophia Nepochataya notifications@github.com:
